// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

/**
 * Protobuf type {@code management.RequestClanInfo}
 */
public final class RequestClanInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:management.RequestClanInfo)
    RequestClanInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestClanInfo.newBuilder() to construct.
  private RequestClanInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestClanInfo() {
    clanOwner_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestClanInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestClanInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            world_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            clanOwner_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.management.ManagementProtos.internal_static_management_RequestClanInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.management.ManagementProtos.internal_static_management_RequestClanInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.management.RequestClanInfo.class, proto.management.RequestClanInfo.Builder.class);
  }

  private int bitField0_;
  public static final int WORLD_FIELD_NUMBER = 1;
  private int world_;
  /**
   * <code>required int32 world = 1;</code>
   * @return Whether the world field is set.
   */
  @java.lang.Override
  public boolean hasWorld() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int32 world = 1;</code>
   * @return The world.
   */
  @java.lang.Override
  public int getWorld() {
    return world_;
  }

  public static final int CLANOWNER_FIELD_NUMBER = 2;
  private volatile java.lang.Object clanOwner_;
  /**
   * <code>required string clanOwner = 2;</code>
   * @return Whether the clanOwner field is set.
   */
  @java.lang.Override
  public boolean hasClanOwner() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string clanOwner = 2;</code>
   * @return The clanOwner.
   */
  @java.lang.Override
  public java.lang.String getClanOwner() {
    java.lang.Object ref = clanOwner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        clanOwner_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string clanOwner = 2;</code>
   * @return The bytes for clanOwner.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClanOwnerBytes() {
    java.lang.Object ref = clanOwner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clanOwner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasWorld()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasClanOwner()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, world_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clanOwner_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, world_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clanOwner_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.management.RequestClanInfo)) {
      return super.equals(obj);
    }
    proto.management.RequestClanInfo other = (proto.management.RequestClanInfo) obj;

    if (hasWorld() != other.hasWorld()) return false;
    if (hasWorld()) {
      if (getWorld()
          != other.getWorld()) return false;
    }
    if (hasClanOwner() != other.hasClanOwner()) return false;
    if (hasClanOwner()) {
      if (!getClanOwner()
          .equals(other.getClanOwner())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorld()) {
      hash = (37 * hash) + WORLD_FIELD_NUMBER;
      hash = (53 * hash) + getWorld();
    }
    if (hasClanOwner()) {
      hash = (37 * hash) + CLANOWNER_FIELD_NUMBER;
      hash = (53 * hash) + getClanOwner().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.management.RequestClanInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.management.RequestClanInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.management.RequestClanInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.management.RequestClanInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.management.RequestClanInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.management.RequestClanInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.management.RequestClanInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.management.RequestClanInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.management.RequestClanInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.management.RequestClanInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.management.RequestClanInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.management.RequestClanInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.management.RequestClanInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code management.RequestClanInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:management.RequestClanInfo)
      proto.management.RequestClanInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.management.ManagementProtos.internal_static_management_RequestClanInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.management.ManagementProtos.internal_static_management_RequestClanInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.management.RequestClanInfo.class, proto.management.RequestClanInfo.Builder.class);
    }

    // Construct using proto.management.RequestClanInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      world_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      clanOwner_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.management.ManagementProtos.internal_static_management_RequestClanInfo_descriptor;
    }

    @java.lang.Override
    public proto.management.RequestClanInfo getDefaultInstanceForType() {
      return proto.management.RequestClanInfo.getDefaultInstance();
    }

    @java.lang.Override
    public proto.management.RequestClanInfo build() {
      proto.management.RequestClanInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.management.RequestClanInfo buildPartial() {
      proto.management.RequestClanInfo result = new proto.management.RequestClanInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.world_ = world_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.clanOwner_ = clanOwner_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.management.RequestClanInfo) {
        return mergeFrom((proto.management.RequestClanInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.management.RequestClanInfo other) {
      if (other == proto.management.RequestClanInfo.getDefaultInstance()) return this;
      if (other.hasWorld()) {
        setWorld(other.getWorld());
      }
      if (other.hasClanOwner()) {
        bitField0_ |= 0x00000002;
        clanOwner_ = other.clanOwner_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasWorld()) {
        return false;
      }
      if (!hasClanOwner()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.management.RequestClanInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.management.RequestClanInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int world_ ;
    /**
     * <code>required int32 world = 1;</code>
     * @return Whether the world field is set.
     */
    @java.lang.Override
    public boolean hasWorld() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 world = 1;</code>
     * @return The world.
     */
    @java.lang.Override
    public int getWorld() {
      return world_;
    }
    /**
     * <code>required int32 world = 1;</code>
     * @param value The world to set.
     * @return This builder for chaining.
     */
    public Builder setWorld(int value) {
      bitField0_ |= 0x00000001;
      world_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 world = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorld() {
      bitField0_ = (bitField0_ & ~0x00000001);
      world_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object clanOwner_ = "";
    /**
     * <code>required string clanOwner = 2;</code>
     * @return Whether the clanOwner field is set.
     */
    public boolean hasClanOwner() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string clanOwner = 2;</code>
     * @return The clanOwner.
     */
    public java.lang.String getClanOwner() {
      java.lang.Object ref = clanOwner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clanOwner_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string clanOwner = 2;</code>
     * @return The bytes for clanOwner.
     */
    public com.google.protobuf.ByteString
        getClanOwnerBytes() {
      java.lang.Object ref = clanOwner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clanOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string clanOwner = 2;</code>
     * @param value The clanOwner to set.
     * @return This builder for chaining.
     */
    public Builder setClanOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      clanOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string clanOwner = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClanOwner() {
      bitField0_ = (bitField0_ & ~0x00000002);
      clanOwner_ = getDefaultInstance().getClanOwner();
      onChanged();
      return this;
    }
    /**
     * <code>required string clanOwner = 2;</code>
     * @param value The bytes for clanOwner to set.
     * @return This builder for chaining.
     */
    public Builder setClanOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      clanOwner_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:management.RequestClanInfo)
  }

  // @@protoc_insertion_point(class_scope:management.RequestClanInfo)
  private static final proto.management.RequestClanInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.management.RequestClanInfo();
  }

  public static proto.management.RequestClanInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestClanInfo>
      PARSER = new com.google.protobuf.AbstractParser<RequestClanInfo>() {
    @java.lang.Override
    public RequestClanInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestClanInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestClanInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestClanInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.management.RequestClanInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

