package core.game.system.command.sets

const val STATS_BASE = "stats_manager"
const val STATS_ENEMIES_KILLED = "enemies_killed"
const val STATS_DEATHS = "deaths"
const val STATS_LOGS = "logs_chopped"
const val STATS_FISH = "fish_caught"
const val STATS_ROCKS = "rocks_mined"
const val STATS_RC = "essence_crafted"
const val STATS_FOOD_COOKED = "food_cooked"
const val STATS_CATS_RAISED = "cats_raised"
const val STATS_PK_KILLS = "player_kills"
const val STATS_PK_DEATHS = "player_deaths"
const val STATS_ALKHARID_GATE = "alkharid_gate"
const val FISHING_TRAWLER_GAMES_WON = "fishing-trawler-games"
const val FISHING_TRAWLER_LEAKS_PATCHED = "fishing-trawler-leaks-patched"
const val FISHING_TRAWLER_SHIPS_SANK = "fishing-trawler-sank"
