{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "queryText": "SELECT * FROM tick_lengths", "rawQueryText": "SELECT * FROM tick_lengths", "timeColumns": [ "ts" ] }
   ]
  },
  {
   "title": "Tick Time By Pulse (Total)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "select * from top_pulses;",
     "rawQueryText": "select * from top_pulses;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "High Volume Pulses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT * FROM high_volume_pulses;",
     "rawQueryText": "SELECT * FROM high_volume_pulses;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bot Population",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT * FROM bot_counts;",
     "rawQueryText": "SELECT * FROM bot_counts;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}